<a href="https://colab.research.google.com/github/JustynaMazurGr/Udemy_data-science-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* @author: krakowiakpawel9@gmail.com  
* @site: e-smartdata.org

### NumPy
>Strona biblioteki: [https://numpy.org/](https://numpy.org/)  
>Dokumentacja: [https://numpy.org/doc/](https://numpy.org/doc/)  
>
>Podstawowa biblioteka do obliczeń numerycznych w języku Python.
>
>Aby zainstalować bibliotekę NumPy, użyj polecenia poniżej:
```
pip install numpy
```

### Spis treści:
1. [Podstawy](#a1)
2. [Typy danych](#a2)
3. [Tworzenie tablic](#a3)
4. [Podstawowe operacje na tablicach](#a4)
5. [Generowanie liczb pseudolosowych](#a5)
6. [Podstawowe funkcje](#a6)
7. [Indeksowanie, Wycinanie](#a7)
8. [Iteracja po tablicach](#a8)
9. [Zmiana rozmiaru tablic](#a9)
10. [Maski logiczne](#a10)


### <a name='a1'></a> Podstawy

In [130]:
import numpy as np
np.__version__  #sprawdzenie wersji numpy

'1.23.5'

In [131]:
print(dir(np))  #sprawdzanie jakie mamy metody do wyboru

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_in

In [132]:
help(np.array)  #wyświetlanie pomocy do funkcji array

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

1D Array

In [133]:
x = np.array([1, 3])  #tworzenie tablicy jednowymiarowej. Tak utworzony obiekt możemy sobie utożsamiać z punktem w przestrzeni R2 lub po prostu z wektorem
x

array([1, 3])

In [134]:
print(x)

[1 3]


In [135]:
type(x) #sprawdzanie typu obiektu. Jest to obiekt klasy ndarray

numpy.ndarray

In [136]:
x.ndim  #pokazuje wymiar tablicy

1

In [137]:
x.shape #wyświetla kształt tablicy (wyświetla 2 bo są dwa elementy w naszej tablicy)

(2,)

In [138]:
x.size  #podaje liczbę elementów w naszej tablicy

2

In [139]:
x.dtype #określa typ danych

dtype('int64')

In [140]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [141]:
x.dtype

dtype('float64')

2D Array

In [142]:
x = np.array([[1, 2], [-3, 1]]) #Jeżeli chcemy sobie zbudować macierz dwuwymiarową podajemy sobie listy, które są zagnieżdżone (czyli listy w liście)
x

array([[ 1,  2],
       [-3,  1]])

In [143]:
x.ndim  #tablica dwuwymiarowa więc ndim wynosi 2

2

In [144]:
x.shape

(2, 2)

In [145]:
x = np.array([[1, 2, 4], [4, 2, 1]])  #tablica z 3 kolumnami i dwoma wierszami
print(x)

[[1 2 4]
 [4 2 1]]


In [146]:
x.shape

(2, 3)

3D Array - pozwalają przechowywać na przykład takie dane jak obraz

In [147]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],

     [[4, 1, 3],
      [4, 2, 1]],

     [[3, 2, 1],
      [4, 3, 2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [148]:
x.ndim

3

In [149]:
x.shape #tu mamy 3 tablice, po dwa wiersze, po 3 kolumny

(3, 2, 3)

### <a name='a2'></a> Typy danych

In [150]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [151]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [152]:
A = np.array([1, 2, 3], dtype='float')  #ustawiamy typ danych na taki jaki chcemy, tu: float
A.dtype

dtype('float64')

In [153]:
A = np.array([1, 2, 3], dtype='complex')  #typ liczb złożonych
A.dtype

dtype('complex128')

In [154]:
A = np.array([1.0, 2.7, 3.3], dtype='int')
A.dtype

dtype('int64')

In [155]:
A     #Pamiętać, że gdy float przekonwertujemy na int to po prostu obcina resztę

array([1, 2, 3])

In [156]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [157]:
A = np.array([24, 120, 230], dtype=np.int8)   #wystarcza do tworzenia obrazów
A.dtype

dtype('int8')

In [158]:
A = np.array([24, 120, 230], dtype=np.uint8)  #uint8 pozwala na użycie wartości od 0 do 255
A.dtype

dtype('uint8')

### <a name='a3'></a> Tworzenie tablic

In [159]:
np.zeros(shape=(4, 10))   #rozmiar: 4 wiersze, 10 kolumn.

#Takie coś może nam służyć - jeżeli będziemy chcieli tworzyć maski do naszych zdjęć przy technikach computer vision, będziemy chcieli utworzyć np. zdjęcie 600x800 pixeli, które zawiera po prostu czarne tło to wtedy użyjemy np. zeros.

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [160]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [161]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [162]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [163]:
np.full(shape=(3, 3), fill_value=4, dtype='int')    #wypełnia tablicę konkrentą wartością

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [164]:
np.arange(10)   #generuje dane podobnie jak range w pythonie

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [165]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [166]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [167]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [168]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [169]:
np.linspace(start=0, stop=1, num=11)    #podobnie jak arange, ale zamiast step jest parametr num czyli ile liczb chcemy mieć wygenerowane w danym przedziale, generuje liczby z równymi odstępami między nimi

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [170]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [171]:
A.reshape((3, 5))   #zmienianie kształtu naszych danych

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [172]:
A.reshape((3, -1))    #tak gdy chcemy 3 wiersze i niech python dobierze odpowiednią liczbę kolumn

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [173]:
A.reshape((-1, 3))    #chcemy 3 kolumny, ale chcemy żeby automatycznie była dobrana liczba wierszy

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### <a name='a4'></a> Podstawowe operacje na tablicach

In [174]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [175]:
A + B   #jeśli dodajemy tablice, to liczba elementów (rozmiar) naszych tablic musi być taka sama (dodaje po kolumnach czyli 3+3, 1+-1)

array([6, 0, 7, 4])

In [176]:
A - B

array([0, 2, 1, 0])

In [177]:
A * B

array([ 9, -1, 12,  4])

In [178]:
A / B   #nie można dzielić przez zero więc pamiętać, aby nie było zer. Przeknwertowuje na float!!!

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [179]:
A + 3   #do każdego elementu tablicy A dodaje pewną stałą (tu 3), można też robić dzielenie, mnożenie, odejmowanie

array([6, 4, 7, 5])

In [180]:
2 * A

array([6, 2, 8, 4])

In [181]:
A + 3*B   #do tablicy A dodana 3 razy tablica B

array([12, -2, 13,  8])

In [182]:
np.add(A, B)    #dodaje dwie tablice (podobnie jak A + B)

array([6, 0, 7, 4])

In [183]:
np.subtract(A, B)   #metoda do odejmowania dwóch tablic (podobnie jak A - M)

array([0, 2, 1, 0])

In [184]:
np.multiply(A, B)   #metoda do mnożenia dwóch tablic (jak A * B)

array([ 9, -1, 12,  4])

In [185]:
np.divide(A, B)   #metoda do dzielenia dwóch tablic (jak A / B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [186]:
#Tworzę dwie macierze
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [187]:
#Mnożenie po elemencie (1*6, 3*0, -2*-1, 0*2)
X * Y

array([[6, 0],
       [2, 0]])

In [188]:
#MNOŻENIE MACIERZOWE (WIERSZ1 RAZY KOLUMNA1 I WIERSZ1 RAZY KOLUMNA2 itd. czyli tu dla pierwszej liczby 1*6+3*-1=6+-3=6-3=3) jak mnoży się macierze: https://www.youtube.com/watch?v=NdbWTxv3GuU

np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [189]:
X.dot(Y)    #zwraca ten sam wynik co wyżej (też mnoży macierzowo X i Y)

array([[  3,   6],
       [-12,   0]])

In [190]:
Y.dot(X)    #pamiętać, że mnożenie macierzy nie jest przemienne, dlatego daje inny wynik

array([[ 6, 18],
       [-5, -3]])

In [191]:
X @ Y   #to też jest mnożenie macierzowe

array([[  3,   6],
       [-12,   0]])

### <a name='a5'></a>  Generowanie liczb pseudolosowych

In [192]:
np.random.seed(0)   #ustalanie ziarna losowania, aby zawsze wynik był taki sam

In [193]:
np.random.randn()   #losowa wartość z rozkładu normalnego

1.764052345967664

In [194]:
np.random.randn(10)   #tablica 10-ciu losowo wygenerowanych elementów z rozkładu normalnego czyli o średniej 0 i odchyleniu standardowym 1

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [195]:
np.random.randn(10, 4)    #możemy liczbę wierszy i kolumn ustalić, kolumny możemy utożsamić z liczbą zmiennych, a wiersze możemy utożsamiać z liczbą próbek

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [196]:
np.random.rand()    #losowa wartość z rozkładu jednostajnego

0.1965823616800535

In [197]:
np.random.rand(10)    #rozkład jednostajny na przedziale [0,1)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [198]:
np.random.rand(10, 2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [199]:
np.random.randint(10)   #zwróci losową liczbę całkowitą nieujemną mniejszą niż 10

3

In [200]:
np.random.randint(low=10, high=101)   #można podać paramentr startowy low i końcowy high

56

In [201]:
np.random.randint(low=10, high=101, size=10)

array([52, 66, 70, 87, 40, 34, 12, 13, 23, 50])

In [202]:
np.random.choice([4, 2, 1, 3, 5])   #losowo wybierze element ze zbioru iterowalnego np. z listy

4

In [203]:
np.random.choice(['python', 'java', 'sql'])

'python'

In [204]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [205]:
np.random.shuffle(data)   #tasowanie naszych danych. PAMIĘTAĆ, ŻE TO ZMIENIA POSTAĆ NASZYCH DANYCH !!!

In [206]:
data

array([6, 9, 1, 5, 0, 7, 3, 4, 8, 2])

### <a name='a6'></a> Podstawowe funkcje

In [207]:
np.exp(1)   #popularna funkcja w uczeniu maszynowym i sieciach neuronowych. Podstawowa funkcja matematyczna exponent. Tu widzimy, że jeśli podniesiemy do 1 to mamy stałą eulera

2.718281828459045

In [208]:
np.sqrt(9)    #zwraca pierwiastek kwadratowy z przekazanej liczby, w typie zawsze float

3.0

In [209]:
np.all([2, 3, 1])   #przechodzi po obiekcie iterowalnych i bada wartości czy zwracają true czy false. Jeśli każda wartość true to zwraca True, jeśli choć jedna zwróci false to ona zwróci False

True

In [210]:
np.any([0, 0, 0])   #sprawdza czy jakikolwiek obiekt jest prawdą, jeśli są same zera to zwraca False -> możemy sprawdzić w ten sposób dużą tablicę składającą się z prawie samych zer i gdzieś gdzieniegdzie jedynek to funkcją any łatwo to sprawdzimy.

False

In [211]:
bool(1.3)   #zwraca False tylko dla zer

True

In [212]:
A = np.random.rand(5)   #Załóżmy, że to co otrzymamy to są prawdopodobieństwa otrzymania poszczególnej klasy dla danej próbki, czyli mamy załóżmy problem klasyfikacji, mamy 5 klas, chcemy którąś klasę przyporządkować, model zwrócił nam wartości prawdopodobieństwi i chcielibyśmy coś z tym zrobić.
A

array([0.29743695, 0.81379782, 0.39650574, 0.8811032 , 0.58127287])

In [213]:
np.argmax(A)    #funkcja, która wyciąga nam indeks najwyższej wartości

3

In [214]:
A[np.argmax(A)]   #tak zrobić jeśli chcę wyciągnąć tę najwyższą wartość z mojej tablicy

0.8811031971111616

In [215]:
np.argmin(A)    #zwróci indeks wartości najniższej

0

In [216]:
np.argsort(A)   #użyteczna funkcja jeśli mamy klasyfikację wieloklasową. Pozwala nam sortować nasze elementy (domyślnie rosnąco) podając odpowiedni inkeks. Jest to też użyteczna funkcja jeśli mamy kilka klas, mamy klasyfikację wieloklasową i chcielibyśmy zwrócić na przykład trzy najbardziej prawdopodobne klasy.

array([0, 2, 4, 1, 3])

In [217]:
np.max(A)   #zwraca wartość max

0.8811031971111616

In [218]:
np.min(A)

0.29743695085513366

In [219]:
np.mean(A)    #policzy średnią

0.5940233162303231

In [220]:
np.median(A)  #policzy medianę

0.5812728726358587

In [221]:
np.std(A)   #policzy odchylenie standardowe

0.2270924608641256

###  <a name='a7'></a> Indeksowanie, Wycinanie

In [222]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [223]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [224]:
A[2]  #wycinam drugi element

2

In [225]:
A[2:] #wycinam od 2 indeksu do końca

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [226]:
A[:2]   #wycinam od początku do 1 !!! (nie do 2)

array([0, 1])

In [227]:
A[[0, 2]]   #wycinam indeks 0 i indeks 2

array([0, 2])

In [228]:
A[-1]   #zwróci ostatni element

19

In [229]:
A[10:15]    #zwróci od 10 do 14 elementu

array([10, 11, 12, 13, 14])

In [230]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [231]:
A[1:3, 1:4]   #wycina elementy z podanego zakresu wierszy i kolumn
              #jeśli zrobimy A[0] to wytniemy cały pierwszy wiersz,
              #A[1] wytniemy wiersz o indeksie 1,
              #A[:,0] jeśli chcemy wyciąć kolumnę (wytniemy kolumnę o podanym indeksie),
              #A[:,-1] wytniemy ostatnią kolumnę
              #A[1,3] wytniemy konkretny jeden element z wiersza o indeksie 1 i kolumny o indeksie 3

array([[ 6,  7,  8],
       [11, 12, 13]])

In [232]:
A[1, 2] = 14    #14 zostało przypisane do tego co było w miejscu A[1,2] czyli na przykład jeśli była tam 5 to zmieniło na 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### <a name='a8'></a> Iteracja po tablicach

In [233]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [234]:
for row in A:     #iterowanie po wierszu
    print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [235]:
for row in A:
    print(row[:3])      #iteruję tylko po tym zakresie (print(row[0]) wyprintowałoby tylko to co jest w wierszach na pozycji 0 czyli pierwszą kolumnę)

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [236]:
for item in A.flat:     #iterowanie po każdym elemencie. Atrybut .flat pozwala wypłaszczyć naszą tablicę i możemy iterować element po elemencie
    print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


### <a name='a9'></a> Zmiana rozmiaru tablic

In [237]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [238]:
A.shape

(4, 5)

In [239]:
A.reshape(5, 4)   #zmiana rozmiaru tablicy

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [240]:
A.ravel()   #pozwala wypłaszczyć nasze dane - postać jednowymiarowa

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [241]:
A.T   #transponowanie tablicy

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

### <a name='a10'></a> Maski logiczne

In [247]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)   #przypomnienie -> tak gdy chcemy 10 wierszy i niech python dobierze odpowiednią liczbę kolumn
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [248]:
A > 0   #To równanie zwróci maskę logiczną na naszą tablicę i zwróci prawdę gdy są wartości >0 i fałsz gdy są<0 i dzięki takiej masce możemy wyciąć tylko te dane, które nas interesują

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [249]:
A[A > 0]    #Przekazując taką maskę do naszej tablicy dostaniemy tylko te elementy, które są dodatnie, czyli tam gdzie wartość jest True

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [244]:
np.bitwise_and(A > -5, A < 5)   #możemy łączyć ze sobą dwa warunki w ten sposób (A[A > -5 and A < 5] zwróciłoby błąd!!!). .bitwise_and zwraca maskę, i zwróci prawdę gdzie oba warunki są spełnione

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [245]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [246]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])